### ISSUE TITLE
TCP New Reno - congesion window - unexpected behaviour

### ISSUE THREAD

**Issue by nivaska** [nyuwireless-unipd/ns3-mmwave#101]
I am working on the example "mmwave-tcp-raytracing-example.cc" with some modifications. I am interested in the TCP congestion window size values.
![out-tcp-cwnd (1)](https://user-images.githubusercontent.com/10324907/54745365-9ca3c900-4bc9-11e9-8071-c9f8b0570027.png)

Eventhough there were no TCP time outs, the congestion window falls to zero periodically. I was expecting it to remain at the constant value after reachin the maximum. Is this the expected behaviour?

**Comment by MengleiZhang** [comment]
From the plot, it seems like TCP timeout keeps happening because of big buffer. One simple way to check TCP timeout event is the congestion window drops to 0 and after that each time congestion window increase 1400 KB (packet size).

To prevent timeout, you can try to reduce the RLC AM/UM buffer to the bandwidth delay product. For example, set buffer size = 100 mbps (rate) x 0.02 s (RTT) = 125 KB.

Config::SetDefault ("ns3::LteRlcAm::MaxTxBufferSize", UintegerValue (125 * 1024));

Here is the results after reducing the buffer size.

![TCP](https://user-images.githubusercontent.com/12700617/54778419-fec0f600-4bea-11e9-98be-0709c3f122a6.png)

**Comment by nivaska** [comment]
Thank you very much for the response. I will try a smaller buffer size. But I did not understand why a RLC large buffer size would cause the TCP time-out, and also why the congeston window drops to 0 instead of dropping to half of its previous value.
