### ISSUE TITLE
throughput TCP mmwave example with multiple UEs

### ISSUE THREAD

**Issue by erazemp** [nyuwireless-unipd/ns3-mmwave#186]
Hi.
I modified the mmwave-tcp-example so that there are 4 devices connected to a single enb node. 3 Ues are only 25m from the enb and 4th is 50m. I set the max speed of data for each device to 1000Mb/s and left the internet dataRate on 100Gb/s.  I also only have 1 remote host. Also the SINR is very high - above 50 for third ue and it still only produces up to 600Mb/s.
I am wondering what is the reason that the 4 nodes cannot operate at full transfer speed and are performing at 400 - 600 Mb/s.
Is it the capacity of the base station?
is it the remote host?
Is it the bandwidth? --> after ./waf run the cmd displays: bandwidth 0 = 1.0001e+09 which means 1Ghz of bandwidth - what does this actually tell me?

Thank you!

**Comment by tommasozugno** [comment]
There may be different reasons, you should carefully analyze the output traces and/or debug your simulation script to understand what's happening. First, I would check if you are losing packets somewhere, e.g., due to TCP/RLC buffer overflows. If not, I would check the behavior of the congestion window to see if TCP is working as expected.

**Comment by erazemp** [comment]
I'm not quite sure how can I determine if there is a packet loss. 
I have created a simulation where I have:
A: 86m, 700Mb/s, 500000
B: 12m, 1500Mb/s, 5000000
C: 23m, 500Mb/s 50000
- 3 ues 86m, 12m and 23m form the base station
- they are all in separate containers
- max throughputs are: 700, 1500, 500 Mb/s
- and have changed the number of packets transmitted so that the third device finishes early --> 500000, 5000000, 50000
- 1 Enb and 1 Remote host

All 3 devices have good SINR and here's what has happened:
Device A: not the focus point because i don't have the rtt graph.
![tp3_01](https://user-images.githubusercontent.com/36954864/101656221-c27a9c80-3a42-11eb-9750-593d03b6944a.png)

Device B: 
![tp3_02](https://user-images.githubusercontent.com/36954864/101656338-e0480180-3a42-11eb-8cf0-d30a603b0a5b.png)
![rtt0](https://user-images.githubusercontent.com/36954864/101656364-e6d67900-3a42-11eb-9457-da212bb9ff68.png)

Device C: 
![tp3_03](https://user-images.githubusercontent.com/36954864/101656388-edfd8700-3a42-11eb-852e-7faed27b47ff.png)
![rtt1](https://user-images.githubusercontent.com/36954864/101656398-f0f87780-3a42-11eb-84ed-c5fa1c3167c2.png)


We can see that B device cannot perform at it's designated maximum speed of 1500Mb/s, while the other 2 (A, C) can. But when the C device finishes it's transmission the rate of device B immediately jumps to it's maximum. Also the RTT extremely lowers at 1.2 seconds which is where the B device finishes. The RTT graph of B is also very interesting.

Could you help me understand the reasons behind this. If this is packet loss or something else? Could it be too many packets sent at once?

Thank you.

**Comment by tommasozugno** [comment]
At first sight I don't see any inconsistency. The available resources are not enough to satisfy the traffic requirements of the three users simultaneously, this is why you see that the throughput of B is limited in the first part of the simulation. The RTT of B is consistent with this observation, since it is high in the first part of the simulation and then decreases when C ends. To explain the behavior of C's RTT you should plot also the congestion window.
