### ISSUE TITLE
Traces usage

### ISSUE THREAD

**Issue by AbdouSadou** [nyuwireless-unipd/ns3-mmwave#46]
Hi,
Can you please explain to me how can i use the DlPDCP and DlRLC trace files to figure out the data rate and delay ? i am more familiar with the ones generated with the LTE helper because they are very detailed (total bytes received etc), and tried to use a pointer to the LTE helper in an exemple simulation (mmwave-epc-tdma) but no data gets saved.
Thanks in advance.

**Comment by mychele** [comment]
Hi,
please consider this wiki page: https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces
If you want to use the LteHelper (and just enable the traces, so that the callbacks are registered), you need to uncomment the lines with the m_txPdu callback in the PDCP and RLC classes. For example:
https://github.com/nyuwireless-unipd/ns3-mmwave/blob/new-handover/src/lte/model/mc-enb-pdcp.cc#L235
Best,
Michele

**Comment by AbdouSadou** [comment]
Thank you !
