### ISSUE TITLE
Is it possible to simulate MU MIMO channel at 3.5 GHz with mmWave?

### ISSUE THREAD

**Issue by Felix-neko** [nyuwireless-unipd/ns3-mmwave#87]
Hi folks! And thank you for you software.

Can you please tell me, is mmWave suitable for simulation of 5G MU MIMO networks below 6 Ghz (for example, 3.5 GHz)?

---
Hope on your answer,
F-lix

**Comment by tommasozugno** [comment]
Hi,
No, it is not. We currently support mmWave channel models only.

Best,
Tommaso

**Comment by debunge** [comment]
@tommasozugno can you tell your estimate on how hard it would be to implement it, given current project architecture and such?

**Comment by mychele** [comment]
Hi,
the main issue is the lack of multiuser support in the channel classes, i.e., currently the model only supports analog beamforming with a single link active in each base station at any given time. In order to support MU-MIMO, you would need to change how the layers from the MAC to the channel work, and this (also including the 3.5 GHz channel model addition) could require a few months.
