### ISSUE TITLE
Mmwave Channel Models SINR Change

### ISSUE THREAD

**Issue by Faydin94** [nyuwireless-unipd/ns3-mmwave#88]
Hi,
I am working on the
 mmwave-simple-building-obstacle for mobile UE scenarios. My questions are about channel models -especially about Beamforming and Propagationloss models-:
1.)Which parameters decide the value of SINR in these models? 
I ran the examples for different velocity values (from 0 to 50 m/s) and I saw that for both channel models SINR has random behavior even for LOS channel state and pathloss model.
Also, the plots of the SINRs are just shifted up or down version of the different velocity cases as you can see below. I could not find the random variable parameter which cause this. 
2.)Where can I find that in beamforming and propagationloss models? 
3.)Does this theoretically true for pathloss model not having decreasing SINR plot for no small scale fading and no shadowing? If yes could you explain the reason?  

Thanks in advance,
Furkan 

![sinr plot](https://user-images.githubusercontent.com/44889685/50423320-d6806000-0864-11e9-9c84-9e760276a41b.PNG)

**Comment by tommasozugno** [comment]
Hi Furkan,

Are you using the default channel (i.e., `MmWave3gppChannel`) and the `BuildingsObstaclePropagationLossModel` pathloss model?

**Comment by Faydin94** [comment]
Hi,
I am using mmwavebeamforming. Actually, I tried Pathloss model and default model taht you mentioned,too. Yet, I could not get what I expect i.e., the results are the same in terms of my questions above.
Regards.

**Comment by tommasozugno** [comment]
Hi,
I'm not sure I have correctly understood your questions, I will try to answer and let me know if I got the point.
- In your plot you can see a step-like behavior. This is because a new channel matrix is periodically generated and so the SINR changes. You can change the periodicity by using the `LongTermUpdatePeriod` or the `UpdatePeriod` attributes of the `MmWaveBeamforming` and the `MmWave3gppChannel` classes, respectively.
- Each step has a different SINR value. This is because the channel generation process itself involves some random parameters, which depends on the particular model you are using.  For instance, `MmWave3gppChannel` implements the channel model described in 3GPP TR 38.900 (in this document you will find all the information about the channel parameters and the generation process)
- If the UE is moving away from the BS you should see that the SINR is decreasing _in average_. In your plot you are considering a small time interval, which may be not representative of the average behavior of the SINR.
- If you need to simulate scenarios in which the mobility of the UEs is relevant, the `MmWave3gppChannel` model supports a spatial consistency feature (see https://arxiv.org/pdf/1702.04822.pdf)

Please, take a look at
- https://arxiv.org/abs/1705.02882 in which you can find a general description of both the 3GPP and the `MmWaveBeamforming` models
- 3GPP TR 38.900 and https://arxiv.org/pdf/1702.04822.pdf for the `MmWave3gppChannel` model

**Comment by Faydin94** [comment]
Thanks for your response. I could solve the sudden change of the channel structure by changing update period parameter. 

When I considered the average SINR I am confused. In the file mmwave/model/mmwave-spectrum-phy.cc line 610 :
 double sinrAvg = Sum (m_sinrPerceived) / (m_sinrPerceived.GetSpectrumModel ()->GetNumBands ());
Why do you set such linear relation and calculate the sinrAvg like this although in mmwave-amc.cc fıle there are nonlinear operations for both SINR and spectral efficiency ?

Best,
Furkan

**Comment by tommasozugno** [comment]
Hi,

sinrAvg it is only used in the trace and it is just a way to express the channel condition, usually it is representative enough. The more complex mapping between sinr and bler is used for all the other operations.

Best,
Tommaso

**Comment by Faydin94** [comment]
Hi,
For tracking the average SINR to verify it decreases by increasing distance between UE and eNB, which SINR in the code should I use or by which modification can I reach this aim?  
Regards,
Furkan

**Comment by tommasozugno** [comment]
Hi,
I think the one in RxPacketTrace will fit your needs.

**Comment by Faydin94** [comment]
Thanks
